### PR TITLE
Remove GetProcAddress + other stuff

### PR DESCRIPTION
**Pull request by S4ntiagoP**
Hello!

The most relevant part of this PR, is that the API `ntdll!GetProcAddress` is not longer used, we now find all the import addresses "by hand" with `xGetProcAddress`.

I found that the `NOHEADERCOPY` option was breaking Beacon for some reason, so what I did is to simply avoid writing the headers if that option was set (we no longer free the memory).  
Feel free to test this out and check if I am right!

I noticed that if you search the address of an API that does not exist, it breaks. That could actually happen if you tried to bypass ETW on an old system, where `ntdll!EtwEventWrite` would not exist.  
This is now fixed and we simply return  NULL and do nothing.

I specified the size of the UDRL to 100K because if you enable all features, the 64-bit loader exceeds the 5K boundary.

Also:
- we now check for NTSTATUS error codes
- removed many casts
- search DLLs with name in ASCII instead of wide string
- check machine type of rdll, so we don't inject a 32-bit PE into a 64-bit process or vise-versa
- when no syscalls are used, removed Virtual* APIs, use Nt* instead
- getSyscallNumber is now coded in asm
- some other very minor changes here and there

I think this is a very robust and reliable UDRL 😄 
Cheers!

### CODE REVIEW

**Comment by boku7** [comment]
Awesome work bro! Cool to see the xGetProcAddress. I was half way through making the function and got lazy and just used the standard API for the import functions that were forwarders, dope to see you finish it out! Just not writing the headers is such a better upgrade than copying and freeing too. You are a beast man! 
Only question is for the 100k UDRL. Does following the advice on the Cobalt Strike support work for this UDRL? Just modding the beacon size in the artifact kit? I haven't tested much with the larger UDRL option so just curious

**Comment by S4ntiagoP** [comment]
Yep, by specifying the size to 100 the UDRL loads withouth any issue, here you have some example output:
```
[22:08:42] ========== Running 'BEACON_RDLL_SIZE' for DLL Name resources/beacon.x64.dll with architecture x64 at BokuLoader.cna:162
[22:08:42] ========== Running 'BEACON_RDLL_GENERATE' for DLL resources/beacon.x64.rl100k.dll with architecture x64 ========== at BokuLoader.cna:132
[22:08:42] Loaded Length: 6996 at BokuLoader.cna:69
[22:08:42] Extracted Length: 5392 at BokuLoader.cna:81
```

Note that the final size is 5392, so more than 5K.

If I remove the "100K size" change we get:
```
[22:10:24] ========== Running 'BEACON_RDLL_SIZE' for DLL Name resources/beacon.x64.dll with architecture x64 at BokuLoader.cna:162
[22:10:24] ========== Running 'BEACON_RDLL_GENERATE' for DLL resources/beacon.x64.dll with architecture x64 ========== at BokuLoader.cna:132
[22:10:24] Loaded Length: 6996 at BokuLoader.cna:69
[22:10:24] Extracted Length: 5392 at BokuLoader.cna:81
[22:10:24] Function call &setup_reflective_loader failed: Reflective DLL Content length (5392) exceeds available space (5122). at BokuLoader.cna:91

```

**Comment by S4ntiagoP** [comment]
The xGetProcAddress function could be improved in the future to be more assembly and less C, but I will let that be for now 😛

**Comment by boku7** [comment]
Nice just saw how you did it. Totally going to be using that in the future for projects😉, great work 🔥

**Pull request merged**
